### ISSUE TITLE
Ruins Invalid Data Report - GS44 - F12

### ISSUE THREAD

**Issue by neilm-fourjs** [canonn-science/RuinsComboMap#11]
## Your CMDR Name: 
CMDR DanteUK

## Which Ruins Site? 
GS44

## Which Obelisk ID? 
F12

## What data did you get? 
Nothing

## What combo did you use? 
Urn + Totem  ( also tried Urn + Relic)

## Other Questions/Comments/Concerns
I'm still there at the moment. I'll try more combo but it's possible it's appearing to do nothing because it's actually returning a datascan I already have - I've checked I don't already have Bio 6 ( but I will check again ) I'm trying to precise with recording what I get from where on my spreadsheet.
[url]https://docs.google.com/spreadsheets/d/1UaG8TU61iMW4bvuezOuwp3mQCpxV57CQBO0CNHlXO88/edit?usp=sharing[/url]

**Comment by derrickmehaffy** [comment]
Pending Review, reported added to Data Sheet

Issue Title updated to reflect report data

**Comment by derrickmehaffy** [comment]
Per Data Sheet: 

Combo should be Urn + Tablet (Confirmed by 2 Canonn Members) for Bio 4
Marking issue as resolved.
