### ISSUE TITLE
Wrong Codex listed for GS17 H3

### ISSUE THREAD

**Issue by CMDRCRUZ** [canonn-science/RuinsComboMap#12]
## Other Questions/Comments/Concerns
Since GS17 is a BETA site, I really doubt that site obelisk H03 will yield History 3 (Betas have Hist 8-18) but  I did try it.

**Comment by derrickmehaffy** [comment]
Data removed from API as we do not have info in sheet, also as stated by report. Unlikely a beta site has History 3
