### ISSUE TITLE
Valid Combo for GS09 R03

### ISSUE THREAD

**Issue by CMDRCRUZ** [canonn-science/RuinsComboMap#13]
## Your CMDR Name: 
CARL CRUZ (aquired From Danteuk's Spreadsheet on FD Forum)

## Which Ruins Site? 
GS09

## Which Obelisk ID? 
R03

## What data did you get? 
Culture 16

## What combo did you use? 
Totem + Casket

**Comment by derrickmehaffy** [comment]
Can confirm this is on our sheet (Pulled from NJM Sheet) Pending further canonn review.

**Comment by derrickmehaffy** [comment]
Per Supafuzz916:

GS09 R03 Combo confirmed Cult 16 Totem+Casket. Added info to the Combo verification spreadsheet. GitHub issue #34 GS09 N13 confirmed as active. This was confirmed as active by myself and Boozeman on the Active Obelisks spreadsheet. Probably got overlooked when transfered to the API. N13 combo confirmed by PeriltheCat as Tech 17 on the combo verification spreadsheet.

**Comment by derrickmehaffy** [comment]
Added to sheet and API, marking as resolved
