### ISSUE TITLE
Valid Combo for GS09 R13

### ISSUE THREAD

**Issue by CMDRCRUZ** [canonn-science/RuinsComboMap#14]
## Your CMDR Name: 
CARL CRUZ (aquired From Danteuk's Spreadsheet on FD Forum)

## Which Ruins Site? 
GS09

## Which Obelisk ID? 
R13

## What data did you get? 
Culture 17

## What combo did you use? 
Totem +Urn

**Comment by derrickmehaffy** [comment]
Has been verified by 3 Canonn Personal as well as NJM Sheet
