### ISSUE TITLE
Invalid Ruins Data GS49 C25

### ISSUE THREAD

**Issue by CMDRMadMalik** [canonn-science/RuinsComboMap#16]
## Your CMDR Name: 
CMDR MadMalik

## Which Ruins Site? 
 GS49

## Which Obelisk ID? 
C25

## What data did you get? 
Language 8

## What combo did you use? 
Tablet + Urn

## Other Questions/Comments/Concerns
The map states that C25 as having no scans available. I was able to produce Language 8 with Tablet + Urn.

**Comment by CMDRMadMalik** [comment]
*Edited for accuracy after further investigation.

**Comment by derrickmehaffy** [comment]
Also confirmed via Data Sheet, This has been verified by one other Canonn Member as Lang 8.

**Comment by derrickmehaffy** [comment]
Pending further Canonn Review before updated in API

**Comment by derrickmehaffy** [comment]
Per Supafuzz916:

GS49 C25 confirmed as Lang 8. Reporter stated they used Tab+Urn but I believe this is a Tab+Any obelisk. Previously confirmed on the Combo Verification by BoozeMan. Updated with my confirmation from today.

**Comment by derrickmehaffy** [comment]
Updated in API, marking as resolved
