### ISSUE TITLE
Ruins Invalid Data Report - GS15 - H22

### ISSUE THREAD

**Issue by RinCat** [canonn-science/RuinsComboMap#17]
## Your CMDR Name: 
CMDR NekoN

## Which Ruins Site? 
GS15

## Which Obelisk ID? 
H22

## What data did you get? 
Language 16

## What combo did you use? 
Tablet + Tablet

**Comment by derrickmehaffy** [comment]
Is currently correct on the Data Sheet, pending an export to the API.

**Comment by derrickmehaffy** [comment]
Updated in API/Sheet, marking as resolved
