### ISSUE TITLE
Ruins Invalid Data Report - GS51 - O12

### ISSUE THREAD

**Issue by RinCat** [canonn-science/RuinsComboMap#18]
## Your CMDR Name: 
CMDR NekoN

## Which Ruins Site? 
GS51

## Which Obelisk ID? 
O12

## What data did you get? 
Don't know

## What combo did you use? 
Totem + ???

## Other Questions/Comments/Concerns
The data is something that I already have, so it's not Technology 6.

**Comment by RinCat** [comment]
It seems a server side bug.
https://forums.frontier.co.uk/showthread.php/346669-Alien-Ruins-Technology-6-bugged-obelisks

**Comment by derrickmehaffy** [comment]
Confirmed Bug, added verification to the Data Sheet as "RPF"

**Comment by derrickmehaffy** [comment]
FDev has pushed out a fix for the beta branch, pending until its pushed out to live build to verify fixed.

**Comment by derrickmehaffy** [comment]
https://forums.frontier.co.uk/showthread.php/359651-Update-2-3-10

>  Installations/POIs/USSs
Fixed an issue whereby the Technology 06 codex entry was missing from Ancient Ruins


Will close once we confirm Tech 6 bug is resolved

**Comment by andybish** [comment]
Confirmed I get Tech 6 from this obelisk now.

**Comment by derrickmehaffy** [comment]
Marking as resolved
