### ISSUE TITLE
Ruins Invalid Data Report - GS3 - N01

### ISSUE THREAD

**Issue by pano696** [canonn-science/RuinsComboMap#20]
## Your CMDR Name: 
CMDR pano696

## Which Ruins Site? 
GS3

## Which Obelisk ID? 
N01

## What data did you get? 
History 3

## What combo did you use? 
Casket + Urn

## Other Questions/Comments/Concerns
Solo mode

**Comment by derrickmehaffy** [comment]
Marking as resolved as this obelisk has been reported before, likely user already has history 3.
