### ISSUE TITLE
Ruins Invalid Data Report - GS7 - O20

### ISSUE THREAD

**Issue by KyleHamar** [canonn-science/RuinsComboMap#23]
## Your CMDR Name: 
Example: CMDR Baron Crusher

## Which Ruins Site? 
Example: #GS7

## Which Obelisk ID? 
Example: O20

## What data did you get? 
Example: nothing

## What combo did you use? 
Example: Orb + Totem

## Other Questions/Comments/Concerns
Technology 6 is bugged it appears.

**Comment by gingters** [comment]
It sadly is. Need to wait for frontier to fix that.
