### ISSUE TITLE
Ruins Invalid Data Report - GS6 - C18

### ISSUE THREAD

**Issue by KiraHozu** [canonn-science/RuinsComboMap#24]
## Your CMDR Name: 
CMDR Kira Nakatani

## Which Ruins Site? 
GS6

## Which Obelisk ID? 
C18

## What data did you get? 
Language 11

## What combo did you use? 
Tablet + Orb

## Other Questions/Comments/Concerns
This orb and all its info to how to get the data from it is simply switched with GS6/C01

**Comment by derrickmehaffy** [comment]
Per Supafuzz916:

GS6 C cluster. Can confirm C01=Lang 12, C18=Lang 11. They were reversed on the combo verification spreadsheet but had not been verified. Updated the spreadsheet with the verified info.

**Comment by andybish** [comment]
Reconfirmed, C18 gave Lang 11, C01 Lang 12

**Comment by derrickmehaffy** [comment]
Added confirmation to sheet, marking as resolved
