### ISSUE TITLE
Ruins Invalid Data Report - GS98 - O12

### ISSUE THREAD

**Issue by gastroent** [canonn-science/RuinsComboMap#25]
## Your CMDR Name: 
CMDR GASTROENT
## Which Ruins Site? 
GS98
## Which Obelisk ID? 
O12
## What data did you get? 
NONE
## What combo did you use? 
ORB + TOTEM
## Other Questions/Comments/Concerns
HAVE TRIED ALL THE SITES WITH TECH 6 OBELISK LISTED NONE HAVE GIVEN ME THE TECH 6 DATA WHICH IS THE LAST PIECE OF DATA I NEED TO COMPLETE RAM TAHS MISSION

**Comment by gingters** [comment]
Tech 6 obelisks are buggy. That's confirmed by Frontier. Mission cannot be completed until Frontier rolls out a fix for that.

**Comment by gastroent** [comment]
Thanks for info awesome piece of work this database
