### ISSUE TITLE
Ruins Invalid Data Report - GS56 - C21

### ISSUE THREAD

**Issue by AurynOfMordor** [canonn-science/RuinsComboMap#26]
***Please note:*** Tech 6 obelisks have been confirmed to be bugged by Frontier. Mission cannot be completed until Frontier rolls out a fix for that.

## Which Ruins Site?
GS56

## Which Obelisk ID?
C21

## What data did you get?
Language 8

## What combo did you use?
Tablet + Tablet

## Other Questions/Comments/Concerns
Open Mode

**Comment by derrickmehaffy** [comment]
Open Mode is not supported at this time, all verification must be done in Solo only. Marking as resolved.
