### ISSUE TITLE
Ruins Invalid Data Report - GS6 - L02

### ISSUE THREAD

**Issue by CMDR-Irene-Adler** [canonn-science/RuinsComboMap#30]
***Please note:*** Tech 6 obelisks have been confirmed to be bugged by Frontier. Mission cannot be completed until Frontier rolls out a fix for that.

## Your CMDR Name:
Example: CMDR Irene Adler

## Which Ruins Site?
Example: GS6

## Which Obelisk ID?
Example: L02

## What data did you get?
Example: No data

## What combo did you use?
Example: Orb + Urn

## Other Questions/Comments/Concerns
I tried different combinations. Orb + Urn is the correct combination, but the data can not be obtained.

**Comment by CMDR-Irene-Adler** [comment]
![untitled](https://user-images.githubusercontent.com/29280547/26935785-82972ad4-4c75-11e7-8d85-80379ad73535.jpg)
Do I understand correctly? To get data on "Technology 10", do I need to scan only one of the obelisks?

**Comment by gingters** [comment]
Correct, you only need to scan one of them to get the data. After that, the second one won't yield the data anymore, as you already have it. (The ingame message that tells you you already have that data is bugged, too).

**Comment by CMDR-Irene-Adler** [comment]
Thanks for the answer. At first I thought I should get two messages from Ram Tah, but I was wrong. I think my ticket can be closed. I got "Technology 10" and there is not any mistake. I apologize for the false alarm.

**Comment by gingters** [comment]
Not a problem at all :) Fly safe, Commander!
