### ISSUE TITLE
Ruins Invalid Data Report - GS9 - N13

### ISSUE THREAD

**Issue by corecache** [canonn-science/RuinsComboMap#34]
***Please note:*** Tech 6 obelisks have been confirmed to be bugged by Frontier. Mission cannot be completed until Frontier rolls out a fix for that.

## Your CMDR Name:
Example: CMDR Several

## Which Ruins Site?
Example: GS09

## Which Obelisk ID?
Example: N13

## Other Questions/Comments/Concerns
N13 is shown on the map https://ruins.canonn.technology/#GS9 as inactive, but it is active.
See http://imgur.com/a/eOAXo

**Comment by derrickmehaffy** [comment]
Per Supafuzz916:

GS09 R03 Combo confirmed Cult 16 Totem+Casket. Added info to the Combo verification spreadsheet. GitHub issue #34 GS09 N13 confirmed as active. This was confirmed as active by myself and Boozeman on the Active Obelisks spreadsheet. Probably got overlooked when transfered to the API. N13 combo confirmed by PeriltheCat as Tech 17 on the combo verification spreadsheet.

**Comment by derrickmehaffy** [comment]
confirmed N13 on the Sheet has the correct data and was listed under active obelisks. API site GS09 was updated to show active. Marking as resolved.
