### ISSUE TITLE
Ruins Invalid Data Report - GS86 - K18

### ISSUE THREAD

**Issue by Savalis** [canonn-science/RuinsComboMap#38]
## Your CMDR Name:
Savaris

## Which Ruins Site?
VELA DARK REGION HB-X C1-28 | E 2 | 11.3, -154.2 (Alpha)

## Which Obelisk ID?
K18

## What data did you get?
None

## What combo did you use?
N/A

## Other Questions/Comments/Concerns
Active ruins for site K have changed. Obelisk K18 is no longer active, and instead, Obelisks K16, & K20 are now active. Currently testing combinations and will add a followup report once the correct combinations have been established. May need to request another CMDR test if resulting data is scan data I've already obtained.

**Comment by derrickmehaffy** [comment]
Per BlackZork:

Combo verification:
SYNUEFE NL-N C23-4 | B 3 | -30.54, -24.2 (Alpha) F20 is Urn+Orb: Biology 5
COL 173 SECTOR KY-Q D5-47 | 9 A | -15.0842, -102.9397 (Alpha) K21 is Orb+Totem: Culture 6

**Comment by derrickmehaffy** [comment]
Brining up in meeting notes on how best to handle changes if its a common occurrence or just a relog issue. Will update after team meeting.

**Comment by andybish** [comment]
Confirming K16 and K20 are active, K17 and K18 are not. Persisted after relog.

**Comment by derrickmehaffy** [comment]
Marked on sheet, pending import to API. Marking as resolved
