### ISSUE TITLE
Valid combo for Gamma R17

### ISSUE THREAD

**Issue by hitchhiker54** [canonn-science/RuinsComboMap#40]
***Please note:*** Tech 6 obelisks have been confirmed to be bugged by Frontier. Mission cannot be completed until Frontier rolls out a fix for that.

## Your CMDR Name:
Dave weyland

## Which Ruins Site?
GS30 COL 173 SECTOR CG-M B24-8 / A 4 @ -42.78, 130.35 (Gamma)

## Which Obelisk ID?
R17

## What data did you get?
History 18

## What combo did you use?
Casket + Casket

**Comment by derrickmehaffy** [comment]
Marked on Spreadsheet as RPF(GH), marking as resolved for confirmed combo
