### ISSUE TITLE
Ruins API Correction: GS119

### ISSUE THREAD

**Issue by andybish** [canonn-science/RuinsComboMap#41]
CMDR ABish

GS119 (Col 173 Sector OC-C b29-1 A 4 21.11, 54.58) (Gamma)

Group C is present, with C14 and C07 lit, though they don't appear on the map for this site.

**Comment by Supafuzz916** [comment]
Can confirm C Cluster as reported by CMDR ABish as well as Lit obelisks C07 and C14.   http://imgur.com/a/8Ysgz
Updated API to reflect the correct information.

**Comment by derrickmehaffy** [comment]
Updated sheet and API, marking as resolved.
