### ISSUE TITLE
Ruins Invalid Data Report - GS41 - E05

### ISSUE THREAD

**Issue by tmitrovich** [canonn-science/RuinsComboMap#42]
***Please note:*** Tech 6 obelisks have been confirmed to be fixed in Patch 2.3.10

## Your CMDR Name: Porkslap
Example: CMDR ChangeMe

## Which Ruins Site? GS41
Example: GS01

## Which Obelisk ID? E05
Example: A01

## What data did you get? Nothing
Example: History 3

## What combo did you use? Orb/Tablet
Example: Casket + Urn

## Other Questions/Comments/Concerns

Looks like section E is backward on this map. I found Tech 11 on E23, not E5.

**Comment by Supafuzz916** [comment]
This information is incorrect. Re-verified the site (for the 4th time) this morning. Active obelisks in E cluster are E05 and E15. THis applies to GitHub issue #43 as well.

**Comment by derrickmehaffy** [comment]
Updated sheet and API, marking as resolved.
