### ISSUE TITLE
Ruins Invalid Data Report - GS25 - C20+21

### ISSUE THREAD

**Issue by andybish** [canonn-science/RuinsComboMap#44]
CMDR ABish

GS25 - HIP 39768 A 14 F -0.01, -149.47 (Beta)

C20+21

I have C20 lit, not C21, although the site shows C21 lit, and C20 not. Both give the same data.

**Comment by Supafuzz916** [comment]
Can confirm C20 is lit not C21. It appears that it may have already been corrected in the API as the map currently shows C20 as lit.

**Comment by derrickmehaffy** [comment]
Updated sheet and API, marking as resolved.
