### ISSUE TITLE
Ruins Invalid Data Report - GS61 - S03

### ISSUE THREAD

**Issue by LenHomme** [canonn-science/RuinsComboMap#47]
***Please note:*** Tech 6 obelisks have been confirmed to be fixed in Patch 2.3.10

## Your CMDR Name:
CMDR Olocrom

## Which Ruins Site?
GS61

## Which Obelisk ID?
S03 and S02 (has to be switched)

## What data did you get?
the S02 works instead of S03 and gives Tech12 instead of Tech13

## What combo did you use?
Orb + Relic

## Other Questions/Comments/Concerns
Playing private group, the combo works but the obelisk is wrong, it's S02 that gives Tech12 instead of Tech13 in obelisk S03
The problem occured in COL 173 SECTOR AP-Q B21-2  | B 4 | -35.3193, -73.9108 (Beta)

**Comment by Supafuzz916** [comment]
Confirmed to be S02 as reported. Updated the API with the correct information. (This was confirmed in both PG and Solo)

**Comment by derrickmehaffy** [comment]
API updated marked as resolved
