### ISSUE TITLE
Ruins Invalid Data Report - GS25 - P02

### ISSUE THREAD

**Issue by mdimarco121** [canonn-science/RuinsComboMap#49]
***Please note:*** Tech 6 obelisks have been confirmed to be fixed in Patch 2.3.10

## Your CMDR Name: Retrograde12
Example: CMDR ChangeMe

## Which Ruins Site? Gs25
Example: GS01

## Which Obelisk ID? p02
Example: A01

## What data did you get? 
Example: History 3

## What combo did you use? totem + relic
Example: Casket + Urn

**Comment by derrickmehaffy** [comment]
Same as https://github.com/canonn-science/RuinsComboMap/issues/50. Marking as resolved as the user did not give any further information
