### ISSUE TITLE
Ruins Invalid Data Report - GS44 - L07

### ISSUE THREAD

**Issue by xPEGGx** [canonn-science/RuinsComboMap#55]
***Please note:*** Tech 6 obelisks have been confirmed to be fixed in Patch 2.3.10

## Your CMDR Name:  
xPEGGx
## Which Ruins Site?
GS44

## Which Obelisk ID?
 L07

## What data did you get?
none

## What combo did you use?
Casket + Totem

**Comment by derrickmehaffy** [comment]
This has been confirmed by at least 4 CMDRs to give History 6, likely the user already has the Data. Marking as resolved
