### ISSUE TITLE
Ruins Invalid Data Report - GS25 - N08

### ISSUE THREAD

**Issue by guirsv1000s** [canonn-science/RuinsComboMap#56]
***Please note:*** Tech 6 obelisks have been confirmed to be fixed in Patch 2.3.10

## Your CMDR Name:
cmdr guirsv1000s
## Which Ruins Site?
GS25

## Which Obelisk ID?
N08

## What data did you get?
??

## What combo did you use?
tablet + orb ( in solo, private group and open mode)

**Comment by derrickmehaffy** [comment]
Has been confirmed by at least 3 other CMDRs to give Language 12, user likely already has Lang12, marking as resolved
