### ISSUE TITLE
Ruins Invalid Data Report - GS35 - C03

### ISSUE THREAD

**Issue by Andjolaw** [canonn-science/RuinsComboMap#59]
***Please note:*** Tech 6 obelisks have been confirmed to be fixed in Patch 2.3.10

## Your CMDR Name: CMDR Anaxagore
Example: CMDR ChangeMe

## Which Ruins Site? GS35
Example: GS01

## Which Obelisk ID? C03
Example: A01

## What data did you get? Nothing
Example: History 3

## What combo did you use? Totem + Casket
Example: Casket + Urn

**Comment by derrickmehaffy** [comment]
User did not provide any additional information, marking as closed
