### ISSUE TITLE
Missing obelisk cluster @ GS36

### ISSUE THREAD

**Issue by CMDR-Nitrogue** [canonn-science/RuinsComboMap#67]
***Please note:*** Tech 6 obelisks have been confirmed to be fixed in Patch 2.3.10

## Which Ruins Site? GS36

Q cluster missing, believe Q6 is active

**Comment by zebarmy** [comment]
![image](https://user-images.githubusercontent.com/28224018/29093838-22157bb4-7c83-11e7-81a7-40348f13b746.png)

Corrected in API
