### ISSUE TITLE
Ruins Invalid Data Report - GS95 - F01 - Broken

### ISSUE THREAD

**Issue by derrickmehaffy** [canonn-science/RuinsComboMap#8]
## Your CMDR Name: 
Supafuzz916 (Reported on Discord)

## Which Ruins Site? 
GS95

## Which Obelisk ID? 
F01

## What data did you get? 
N/A - Status Broken

## What combo did you use? 
N/A

## Other Questions/Comments/Concerns
Pending Further Review from other Sites

**Comment by derrickmehaffy** [comment]
Will need to verify this at other sites to have map changed.

For now hold off on it, until we have a few other sites checked. So far no one has listed F01 in any of the Active Obelisk reports: http://i.imgur.com/0Jqpvn5.png

**Comment by CmdrAdama** [comment]
Will do.  Once confirmed the API data can be updated and this issue closed

**Comment by derrickmehaffy** [comment]
API confirmed broken, marking as resolved
