### ISSUE TITLE
Show Obelisk Combo Verification Status from API

### ISSUE THREAD

**Issue by derrickmehaffy** [canonn-science/RuinsComboMap#9]
Pending on https://github.com/canonn-science/CanonnApi/issues/28

SoulStah was going to work on making a small "Verified by Canonn" Graphic to show on a "True" Value else we can find some small red X graphic to show when "False"

**Comment by gingters** [comment]
Will be deployed to API with production release 1.1.0.
The `v1/maps/scandata` endpoint will now show the verification state for each obelisk:

```
{
  "alpha": {
    "a": {
      "1": {
        "scan": "Language 1",
        "isVerified": true,
        "items": [
          "Tablet"
        ]
      },
      "2": {
        "scan": "Language 1",
        "isVerified": false,
        "items": [
          "Tablet"
        ]
      },...
```

**Comment by CmdrAdama** [comment]
Added in commit 6c3b30b
